POST http://localhost:5000/api/portfolio/sendMail
Content-Type: application/json

{
  "name": "Maria",
  "email": "marb2898@gmail.com",
  "message": "Este es un mensaje de prueba que mando desde la API"
}